[package]
name = "nimage"
version = "0.2.0-dev"
authors = ["Allen Wild <allenwild93@gmail.com>"]
license = "GPL-3.0-or-later"
edition = "2018"

[dependencies]
anyhow = "1.0.31"
clap = "2.33.1"

[[bin]]
name = "mknImage"
path = "src/mknImage/main.rs"
