[package]
name = "nimage"
version = "0.1.0"
authors = ["Allen Wild <allenwild93@gmail.com>"]
license = "GPL-3.0-or-later"
edition = "2018"

[dependencies]
clap = "2.33.1"

[[bin]]
# should be mknImage but cargo sets the bin name as a crate name,
# causing snake case warnings.
name = "mknImage"
path = "src/mknImage/main.rs"
